# Message constants

# Timer module
int16 MSG_TIMER_TICK =                    11
int16 MSG_TIMER_TICK_1S =                 12 
int16 MSG_TIMER_TICK_1M =                 13

# Navigation module
int16 MSG_NAVIGATION_PATH_FOUND =         21
int16 MSG_NAVIGATION_PATH_NOT_FOUND =     22
int16 MSG_NAVIGATION_MOVE_COMPLETED =     23
int16 MSG_NAVIGATION_COLLISION_WARNING =  24
int16 MSG_NAVIGATION_COLLISION_DETECTED = 25

# Message code
int16 code
